$(call PKG_INIT_BIN, 2.41)
$(PKG)_SOURCE:=binutils-$($(PKG)_VERSION).tar.xz
$(PKG)_HASH:=ae9a5789e23459e59606e6714723f2d3ffc31c03174191ef0d015bdf06007450
$(PKG)_SITE:=https://ftp.gnu.org/gnu/binutils,https://mirror.dogado.de/gnu/binutils
### WEBSITE:=https://www.gnu.org/software/binutils/
### MANPAGE:=https://sourceware.org/binutils/docs/
### CHANGES:=https://sourceware.org/binutils/docs-2.41/binutils/
### CVSREPO:=https://sourceware.org/git/binutils-gdb.git
### SUPPORT:=Ircama

# Patchelf configuration - using version 0.18.0 with dynamic libstdc++ linking
BINARY_TOOLS_PATCHELF_VERSION:=0.18.0
BINARY_TOOLS_PATCHELF_SOURCE:=patchelf-$(BINARY_TOOLS_PATCHELF_VERSION).tar.bz2
BINARY_TOOLS_PATCHELF_HASH:=e9dc4d53c2db7a31fd2c0d0e4b0e6b89d2d87e3fb1ba92b001f8f32432bb3444
BINARY_TOOLS_PATCHELF_SITE:=https://github.com/NixOS/patchelf/releases/download/$(BINARY_TOOLS_PATCHELF_VERSION)
BINARY_TOOLS_PATCHELF_DIR:=$(BINARY_TOOLS_SOURCE_DIR)/patchelf-$(BINARY_TOOLS_PATCHELF_VERSION)

# Define build and target locations for each binary following file.mk pattern
BINARY_TOOLS_READELF_BUILD := $(BINARY_TOOLS_DIR)/binutils/readelf
BINARY_TOOLS_READELF_TARGET := $(BINARY_TOOLS_DEST_DIR)/usr/bin/readelf

BINARY_TOOLS_OBJDUMP_BUILD := $(BINARY_TOOLS_DIR)/binutils/objdump
BINARY_TOOLS_OBJDUMP_TARGET := $(BINARY_TOOLS_DEST_DIR)/usr/bin/objdump

BINARY_TOOLS_OBJCOPY_BUILD := $(BINARY_TOOLS_DIR)/binutils/objcopy
BINARY_TOOLS_OBJCOPY_TARGET := $(BINARY_TOOLS_DEST_DIR)/usr/bin/objcopy

BINARY_TOOLS_NM_BUILD := $(BINARY_TOOLS_DIR)/binutils/nm-new
BINARY_TOOLS_NM_TARGET := $(BINARY_TOOLS_DEST_DIR)/usr/bin/nm

BINARY_TOOLS_STRINGS_BUILD := $(BINARY_TOOLS_DIR)/binutils/strings
BINARY_TOOLS_STRINGS_TARGET := $(BINARY_TOOLS_DEST_DIR)/usr/bin/strings

BINARY_TOOLS_AR_BUILD := $(BINARY_TOOLS_DIR)/binutils/ar
BINARY_TOOLS_AR_TARGET := $(BINARY_TOOLS_DEST_DIR)/usr/bin/ar

BINARY_TOOLS_RANLIB_BUILD := $(BINARY_TOOLS_DIR)/binutils/ranlib
BINARY_TOOLS_RANLIB_TARGET := $(BINARY_TOOLS_DEST_DIR)/usr/bin/ranlib

BINARY_TOOLS_STRIP_BUILD := $(BINARY_TOOLS_DIR)/binutils/strip-new
BINARY_TOOLS_STRIP_TARGET := $(BINARY_TOOLS_DEST_DIR)/usr/bin/strip

BINARY_TOOLS_ADDR2LINE_BUILD := $(BINARY_TOOLS_DIR)/binutils/addr2line
BINARY_TOOLS_ADDR2LINE_TARGET := $(BINARY_TOOLS_DEST_DIR)/usr/bin/addr2line

BINARY_TOOLS_SIZE_BUILD := $(BINARY_TOOLS_DIR)/binutils/size
BINARY_TOOLS_SIZE_TARGET := $(BINARY_TOOLS_DEST_DIR)/usr/bin/size

BINARY_TOOLS_PATCHELF_BUILD := $(BINARY_TOOLS_PATCHELF_DIR)/src/patchelf
BINARY_TOOLS_PATCHELF_TARGET := $(BINARY_TOOLS_DEST_DIR)/usr/bin/patchelf

# Conditional tool inclusion based on user selection
BINARY_TOOLS_SELECTED :=
BINARY_TOOLS_TARGETS_PRECOMPILED :=

ifeq ($(strip $(FREETZ_PACKAGE_BINARY_TOOLS_READELF)),y)
BINARY_TOOLS_SELECTED += readelf
BINARY_TOOLS_TARGETS_PRECOMPILED += $(BINARY_TOOLS_READELF_TARGET)
$(PKG)_EXCLUDED := $(filter-out usr/bin/readelf,$($(PKG)_EXCLUDED))
else
$(PKG)_EXCLUDED += usr/bin/readelf
endif

ifeq ($(strip $(FREETZ_PACKAGE_BINARY_TOOLS_OBJDUMP)),y)
BINARY_TOOLS_SELECTED += objdump
BINARY_TOOLS_TARGETS_PRECOMPILED += $(BINARY_TOOLS_OBJDUMP_TARGET)
$(PKG)_EXCLUDED := $(filter-out usr/bin/objdump,$($(PKG)_EXCLUDED))
else
$(PKG)_EXCLUDED += usr/bin/objdump
endif

ifeq ($(strip $(FREETZ_PACKAGE_BINARY_TOOLS_OBJCOPY)),y)
BINARY_TOOLS_SELECTED += objcopy
BINARY_TOOLS_TARGETS_PRECOMPILED += $(BINARY_TOOLS_OBJCOPY_TARGET)
$(PKG)_EXCLUDED := $(filter-out usr/bin/objcopy,$($(PKG)_EXCLUDED))
else
$(PKG)_EXCLUDED += usr/bin/objcopy
endif

ifeq ($(strip $(FREETZ_PACKAGE_BINARY_TOOLS_NM)),y)
BINARY_TOOLS_SELECTED += nm
BINARY_TOOLS_TARGETS_PRECOMPILED += $(BINARY_TOOLS_NM_TARGET)
$(PKG)_EXCLUDED := $(filter-out usr/bin/nm,$($(PKG)_EXCLUDED))
else
$(PKG)_EXCLUDED += usr/bin/nm
endif

ifeq ($(strip $(FREETZ_PACKAGE_BINARY_TOOLS_STRINGS)),y)
BINARY_TOOLS_SELECTED += strings
BINARY_TOOLS_TARGETS_PRECOMPILED += $(BINARY_TOOLS_STRINGS_TARGET)
$(PKG)_EXCLUDED := $(filter-out usr/bin/strings,$($(PKG)_EXCLUDED))
else
$(PKG)_EXCLUDED += usr/bin/strings
endif

ifeq ($(strip $(FREETZ_PACKAGE_BINARY_TOOLS_AR)),y)
BINARY_TOOLS_SELECTED += ar
BINARY_TOOLS_TARGETS_PRECOMPILED += $(BINARY_TOOLS_AR_TARGET)
$(PKG)_EXCLUDED := $(filter-out usr/bin/ar,$($(PKG)_EXCLUDED))
else
$(PKG)_EXCLUDED += usr/bin/ar
endif

ifeq ($(strip $(FREETZ_PACKAGE_BINARY_TOOLS_RANLIB)),y)
BINARY_TOOLS_SELECTED += ranlib
BINARY_TOOLS_TARGETS_PRECOMPILED += $(BINARY_TOOLS_RANLIB_TARGET)
$(PKG)_EXCLUDED := $(filter-out usr/bin/ranlib,$($(PKG)_EXCLUDED))
else
$(PKG)_EXCLUDED += usr/bin/ranlib
endif

ifeq ($(strip $(FREETZ_PACKAGE_BINARY_TOOLS_STRIP)),y)
BINARY_TOOLS_SELECTED += strip
BINARY_TOOLS_TARGETS_PRECOMPILED += $(BINARY_TOOLS_STRIP_TARGET)
$(PKG)_EXCLUDED := $(filter-out usr/bin/strip,$($(PKG)_EXCLUDED))
else
$(PKG)_EXCLUDED += usr/bin/strip
endif

ifeq ($(strip $(FREETZ_PACKAGE_BINARY_TOOLS_ADDR2LINE)),y)
BINARY_TOOLS_SELECTED += addr2line
BINARY_TOOLS_TARGETS_PRECOMPILED += $(BINARY_TOOLS_ADDR2LINE_TARGET)
$(PKG)_EXCLUDED := $(filter-out usr/bin/addr2line,$($(PKG)_EXCLUDED))
else
$(PKG)_EXCLUDED += usr/bin/addr2line
endif

ifeq ($(strip $(FREETZ_PACKAGE_BINARY_TOOLS_SIZE)),y)
BINARY_TOOLS_SELECTED += size
BINARY_TOOLS_TARGETS_PRECOMPILED += $(BINARY_TOOLS_SIZE_TARGET)
$(PKG)_EXCLUDED := $(filter-out usr/bin/size,$($(PKG)_EXCLUDED))
else
$(PKG)_EXCLUDED += usr/bin/size
endif

ifeq ($(strip $(FREETZ_PACKAGE_BINARY_TOOLS_PATCHELF)),y)
BINARY_TOOLS_SELECTED += patchelf
BINARY_TOOLS_TARGETS_PRECOMPILED += $(BINARY_TOOLS_PATCHELF_TARGET)
$(PKG)_EXCLUDED := $(filter-out usr/bin/patchelf,$($(PKG)_EXCLUDED))
else
$(PKG)_EXCLUDED += usr/bin/patchelf
endif

$(PKG)_CONFIGURE_OPTIONS += --target=$(REAL_GNU_TARGET_NAME)
$(PKG)_CONFIGURE_OPTIONS += --disable-shared
$(PKG)_CONFIGURE_OPTIONS += --enable-static
$(PKG)_CONFIGURE_OPTIONS += --disable-multilib
$(PKG)_CONFIGURE_OPTIONS += --disable-werror
$(PKG)_CONFIGURE_OPTIONS += --disable-sim
$(PKG)_CONFIGURE_OPTIONS += --disable-gdb
$(PKG)_CONFIGURE_OPTIONS += --without-included-gettext
$(PKG)_CONFIGURE_OPTIONS += --enable-deterministic-archives


# Standard download and unpack for binutils
$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)

# Download and unpack patchelf 0.18.0 (no patches needed with dynamic libstdc++)
$(BINARY_TOOLS_PATCHELF_DIR)/.unpacked: $(DL_DIR)/$(BINARY_TOOLS_PATCHELF_SOURCE) | $(BINARY_TOOLS_SOURCE_DIR) $(UNPACK_TARBALL_PREREQUISITES)
	@$(call _ECHO,unpacking patchelf $(BINARY_TOOLS_PATCHELF_VERSION) for target)
	$(RM) -r $(BINARY_TOOLS_PATCHELF_DIR)
	mkdir -p $(BINARY_TOOLS_PATCHELF_DIR)
	$(call UNPACK_TARBALL,$(DL_DIR)/$(BINARY_TOOLS_PATCHELF_SOURCE),$(BINARY_TOOLS_PATCHELF_DIR),1)
	touch $@

# Custom configuration for binutils
$(BINARY_TOOLS_DIR)/.configured: $(BINARY_TOOLS_DIR)/.unpacked | $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libc.a
	mkdir -p $(BINARY_TOOLS_DIR)
	(cd $(BINARY_TOOLS_DIR); rm -f config.cache; \
		$(TARGET_CONFIGURE_ENV) \
		$(FREETZ_BASE_DIR)/$(BINARY_TOOLS_DIR)/configure \
		--build=$(GNU_HOST_NAME) \
		--host=$(GNU_TARGET_NAME) \
		--prefix=/usr \
		$(BINARY_TOOLS_CONFIGURE_OPTIONS) \
	);
	touch $@

# Patchelf configuration (bypass wrapper to use libstdc++ instead of uClibc++)
# Use dynamic linking with libstdc++ from /usr/lib/freetz (RPATH already configured)
$(BINARY_TOOLS_PATCHELF_DIR)/.configured: $(BINARY_TOOLS_PATCHELF_DIR)/.unpacked | $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libc.a
	(cd $(BINARY_TOOLS_PATCHELF_DIR); \
		$(AUTORECONF) \
		rm -f config.cache; \
		$(TARGET_CONFIGURE_ENV) \
		CXX="$(TARGET_CROSS)g++" \
		./configure \
		$(TARGET_CONFIGURE_OPTIONS) \
	);
	touch $@

$(BINARY_TOOLS_READELF_BUILD) $(BINARY_TOOLS_OBJDUMP_BUILD) $(BINARY_TOOLS_OBJCOPY_BUILD) $(BINARY_TOOLS_NM_BUILD) $(BINARY_TOOLS_STRINGS_BUILD) $(BINARY_TOOLS_AR_BUILD) $(BINARY_TOOLS_RANLIB_BUILD) $(BINARY_TOOLS_STRIP_BUILD) $(BINARY_TOOLS_ADDR2LINE_BUILD) $(BINARY_TOOLS_SIZE_BUILD): $(BINARY_TOOLS_DIR)/.configured
	$(SUBMAKE) -C $(BINARY_TOOLS_DIR)

$(BINARY_TOOLS_PATCHELF_BUILD): $(BINARY_TOOLS_PATCHELF_DIR)/.configured
	$(SUBMAKE) -C $(BINARY_TOOLS_PATCHELF_DIR)

$(BINARY_TOOLS_READELF_TARGET): $(BINARY_TOOLS_READELF_BUILD)
	$(INSTALL_BINARY_STRIP)

$(BINARY_TOOLS_OBJDUMP_TARGET): $(BINARY_TOOLS_OBJDUMP_BUILD)
	$(INSTALL_BINARY_STRIP)

$(BINARY_TOOLS_OBJCOPY_TARGET): $(BINARY_TOOLS_OBJCOPY_BUILD)
	$(INSTALL_BINARY_STRIP)

$(BINARY_TOOLS_NM_TARGET): $(BINARY_TOOLS_NM_BUILD)
	$(INSTALL_BINARY_STRIP)

$(BINARY_TOOLS_STRINGS_TARGET): $(BINARY_TOOLS_STRINGS_BUILD)
	$(INSTALL_BINARY_STRIP)

$(BINARY_TOOLS_AR_TARGET): $(BINARY_TOOLS_AR_BUILD)
	$(INSTALL_BINARY_STRIP)

$(BINARY_TOOLS_RANLIB_TARGET): $(BINARY_TOOLS_RANLIB_BUILD)
	$(INSTALL_BINARY_STRIP)

$(BINARY_TOOLS_STRIP_TARGET): $(BINARY_TOOLS_STRIP_BUILD)
	$(INSTALL_BINARY_STRIP)

$(BINARY_TOOLS_ADDR2LINE_TARGET): $(BINARY_TOOLS_ADDR2LINE_BUILD)
	$(INSTALL_BINARY_STRIP)

$(BINARY_TOOLS_SIZE_TARGET): $(BINARY_TOOLS_SIZE_BUILD)
	$(INSTALL_BINARY_STRIP)

$(BINARY_TOOLS_PATCHELF_TARGET): $(BINARY_TOOLS_PATCHELF_BUILD)
	$(INSTALL_BINARY_STRIP)

$(pkg):

$(pkg)-precompiled: $(BINARY_TOOLS_TARGETS_PRECOMPILED)

$(pkg)-clean:
	-$(SUBMAKE) -C $(BINARY_TOOLS_DIR) clean
	-$(SUBMAKE) -C $(BINARY_TOOLS_PATCHELF_DIR) clean

$(pkg)-uninstall:
	$(RM) $(BINARY_TOOLS_READELF_TARGET) $(BINARY_TOOLS_OBJDUMP_TARGET) $(BINARY_TOOLS_OBJCOPY_TARGET) $(BINARY_TOOLS_NM_TARGET) $(BINARY_TOOLS_STRINGS_TARGET) $(BINARY_TOOLS_AR_TARGET) $(BINARY_TOOLS_RANLIB_TARGET) $(BINARY_TOOLS_STRIP_TARGET) $(BINARY_TOOLS_ADDR2LINE_TARGET) $(BINARY_TOOLS_SIZE_TARGET) $(BINARY_TOOLS_PATCHELF_TARGET)

$(PKG_FINISH)