package Errno;
our $VERSION = '1.37';

# Stub implementation for microperl
# %! is not fully supported, but provide minimal functionality

use Exporter 'import';
our @EXPORT = qw(
    ENOENT EINTR EIO ENXIO E2BIG ENOEXEC EBADF ECHILD EAGAIN EWOULDBLOCK
    ENOMEM EACCES EFAULT ENOTBLK EBUSY EEXIST EXDEV ENODEV ENOTDIR EISDIR
    EINVAL ENFILE EMFILE ENOTTY ETXTBSY EFBIG ENOSPC ESPIPE EROFS EMLINK
    EPIPE EDOM ERANGE EDEADLK ENAMETOOLONG ENOLCK ENOSYS ENOTEMPTY ELOOP
    ENOMSG EIDRM ECHRNG EL2NSYNC EL3HLT EL3RST ELNRNG EUNATCH ENOCSI EL2HLT
    EBADE EBADR EXFULL ENOANO EBADRQC EBADSLT EDEADLOCK EBFONT ENOSTR ENODATA
    ETIME ENOSR ENONET ENOPKG EREMOTE ENOLINK EADV ESRMNT ECOMM EPROTO
    EMULTIHOP EDOTDOT EBADMSG EOVERFLOW ENOTUNIQ EBADFD EREMCHG ELIBACC
    ELIBBAD ELIBSCN ELIBMAX ELIBEXEC EILSEQ ERESTART ESTRPIPE EUSERS ENOTSOCK
    EDESTADDRREQ EMSGSIZE EPROTOTYPE ENOPROTOOPT EPROTONOSUPPORT ESOCKTNOSUPPORT
    EOPNOTSUPP EPFNOSUPPORT EAFNOSUPPORT EADDRINUSE EADDRNOTAVAIL ENETDOWN
    ENETUNREACH ENETRESET ECONNABORTED ECONNRESET ENOBUFS EISCONN ENOTCONN
    ESHUTDOWN ETOOMANYREFS ETIMEDOUT ECONNREFUSED EHOSTDOWN EHOSTUNREACH
    EINPROGRESS EALREADY EWOULDBLOCK EINPROGRESS EISCONN ENOTCONN ESHUTDOWN
    ETOOMANYREFS ETIMEDOUT ECONNREFUSED EHOSTDOWN EHOSTUNREACH ENETRESET
    ENOBUFS EISCONN ENOTCONN ESHUTDOWN ETOOMANYREFS ETIMEDOUT ECONNREFUSED
    EHOSTDOWN EHOSTUNREACH
);

sub _tie_it {
    # Stub: do nothing
}

# Define errno constants (dummy values for microperl)
sub ENOENT { 2 }
sub EINTR { 4 }
sub EIO { 5 }
sub ENXIO { 6 }
sub E2BIG { 7 }
sub ENOEXEC { 8 }
sub EBADF { 9 }
sub ECHILD { 10 }
sub EAGAIN { 11 }
sub EWOULDBLOCK { 11 }
sub ENOMEM { 12 }
sub EACCES { 13 }
sub EFAULT { 14 }
sub ENOTBLK { 15 }
sub EBUSY { 16 }
sub EEXIST { 17 }
sub EXDEV { 18 }
sub ENODEV { 19 }
sub ENOTDIR { 20 }
sub EISDIR { 21 }
sub EINVAL { 22 }
sub ENFILE { 23 }
sub EMFILE { 24 }
sub ENOTTY { 25 }
sub ETXTBSY { 26 }
sub EFBIG { 27 }
sub ENOSPC { 28 }
sub ESPIPE { 29 }
sub EROFS { 30 }
sub EMLINK { 31 }
sub EPIPE { 32 }
sub EDOM { 33 }
sub ERANGE { 34 }
sub EDEADLK { 35 }
sub ENAMETOOLONG { 36 }
sub ENOLCK { 37 }
sub ENOSYS { 38 }
sub ENOTEMPTY { 39 }
sub ELOOP { 40 }
sub ENOMSG { 42 }
sub EIDRM { 43 }
sub ECHRNG { 44 }
sub EL2NSYNC { 45 }
sub EL3HLT { 46 }
sub EL3RST { 47 }
sub ELNRNG { 48 }
sub EUNATCH { 49 }
sub ENOCSI { 50 }
sub EL2HLT { 51 }
sub EBADE { 52 }
sub EBADR { 53 }
sub EXFULL { 54 }
sub ENOANO { 55 }
sub EBADRQC { 56 }
sub EBADSLT { 57 }
sub EDEADLOCK { 58 }
sub EBFONT { 59 }
sub ENOSTR { 60 }
sub ENODATA { 61 }
sub ETIME { 62 }
sub ENOSR { 63 }
sub ENONET { 64 }
sub ENOPKG { 65 }
sub EREMOTE { 66 }
sub ENOLINK { 67 }
sub EADV { 68 }
sub ESRMNT { 69 }
sub ECOMM { 70 }
sub EPROTO { 71 }
sub EMULTIHOP { 72 }
sub EDOTDOT { 73 }
sub EBADMSG { 74 }
sub EOVERFLOW { 75 }
sub ENOTUNIQ { 76 }
sub EBADFD { 77 }
sub EREMCHG { 78 }
sub ELIBACC { 79 }
sub ELIBBAD { 80 }
sub ELIBSCN { 81 }
sub ELIBMAX { 82 }
sub ELIBEXEC { 83 }
sub EILSEQ { 84 }
sub ERESTART { 85 }
sub ESTRPIPE { 86 }
sub EUSERS { 87 }
sub ENOTSOCK { 88 }
sub EDESTADDRREQ { 89 }
sub EMSGSIZE { 90 }
sub EPROTOTYPE { 91 }
sub ENOPROTOOPT { 92 }
sub EPROTONOSUPPORT { 93 }
sub ESOCKTNOSUPPORT { 94 }
sub EOPNOTSUPP { 95 }
sub EPFNOSUPPORT { 96 }
sub EAFNOSUPPORT { 97 }
sub EADDRINUSE { 98 }
sub EADDRNOTAVAIL { 99 }
sub ENETDOWN { 100 }
sub ENETUNREACH { 101 }
sub ENETRESET { 102 }
sub ECONNABORTED { 103 }
sub ECONNRESET { 104 }
sub ENOBUFS { 105 }
sub EISCONN { 106 }
sub ENOTCONN { 107 }
sub ESHUTDOWN { 108 }
sub ETOOMANYREFS { 109 }
sub ETIMEDOUT { 110 }
sub ECONNREFUSED { 111 }
sub EHOSTDOWN { 112 }
sub EHOSTUNREACH { 113 }
sub EINPROGRESS { 115 }
sub EALREADY { 114 }
sub EWOULDBLOCK { 11 }
sub EINPROGRESS { 115 }
sub EISCONN { 106 }
sub ENOTCONN { 107 }
sub ESHUTDOWN { 108 }
sub ETOOMANYREFS { 109 }
sub ETIMEDOUT { 110 }
sub ECONNREFUSED { 111 }
sub EHOSTDOWN { 112 }
sub EHOSTUNREACH { 113 }
sub ENETRESET { 102 }
sub ENOBUFS { 105 }
sub EISCONN { 106 }
sub ENOTCONN { 107 }
sub ESHUTDOWN { 108 }
sub ETOOMANYREFS { 109 }
sub ETIMEDOUT { 110 }
sub ECONNREFUSED { 111 }
sub EHOSTDOWN { 112 }
sub EHOSTUNREACH { 113 }
sub ENOMEM { 12 }
sub EACCES { 13 }
sub EFAULT { 14 }
sub ENOTBLK { 15 }
sub EBUSY { 16 }
sub EEXIST { 17 }
sub EXDEV { 18 }
sub ENODEV { 19 }
sub ENOTDIR { 20 }
sub EISDIR { 21 }
sub EINVAL { 22 }
sub ENFILE { 23 }
sub EMFILE { 24 }
sub ENOTTY { 25 }
sub ETXTBSY { 26 }
sub EFBIG { 27 }
sub ENOSPC { 28 }
sub ESPIPE { 29 }
sub EROFS { 30 }
sub EMLINK { 31 }
sub EPIPE { 32 }
sub EDOM { 33 }
sub ERANGE { 34 }
sub EDEADLK { 35 }
sub ENAMETOOLONG { 36 }
sub ENOLCK { 37 }
sub ENOSYS { 38 }
sub ENOTEMPTY { 39 }
sub ELOOP { 40 }
sub ENOMSG { 42 }
sub EIDRM { 43 }
sub ECHRNG { 44 }
sub EL2NSYNC { 45 }
sub EL3HLT { 46 }
sub EL3RST { 47 }
sub ELNRNG { 48 }
sub EUNATCH { 49 }
sub ENOCSI { 50 }
sub EL2HLT { 51 }
sub EBADE { 52 }
sub EBADR { 53 }
sub EXFULL { 54 }
sub ENOANO { 55 }
sub EBADRQC { 56 }
sub EBADSLT { 57 }
sub EDEADLOCK { 35 }
sub EBFONT { 59 }
sub ENOSTR { 60 }
sub ENODATA { 61 }
sub ETIME { 62 }
sub ENOSR { 63 }
sub ENONET { 64 }
sub ENOPKG { 65 }
sub EREMOTE { 66 }
sub ENOLINK { 67 }
sub EADV { 68 }
sub ESRMNT { 69 }
sub ECOMM { 70 }
sub EPROTO { 71 }
sub EMULTIHOP { 72 }
sub EDOTDOT { 73 }
sub EBADMSG { 74 }
sub EOVERFLOW { 75 }
sub ENOTUNIQ { 76 }
sub EBADFD { 77 }
sub EREMCHG { 78 }
sub ELIBACC { 79 }
sub ELIBBAD { 80 }
sub ELIBSCN { 81 }
sub ELIBMAX { 82 }
sub ELIBEXEC { 83 }
sub EILSEQ { 84 }
sub ERESTART { 85 }
sub ESTRPIPE { 86 }
sub EUSERS { 87 }
sub ENOTSOCK { 88 }
sub EDESTADDRREQ { 89 }
sub EMSGSIZE { 90 }
sub EPROTOTYPE { 91 }
sub ENOPROTOOPT { 92 }
sub EPROTONOSUPPORT { 93 }
sub ESOCKTNOSUPPORT { 94 }
sub EOPNOTSUPP { 95 }
sub EPFNOSUPPORT { 96 }
sub EAFNOSUPPORT { 97 }
sub EADDRINUSE { 98 }
sub EADDRNOTAVAIL { 99 }
sub ENETDOWN { 100 }
sub ENETUNREACH { 101 }
sub ENETRESET { 102 }
sub ECONNABORTED { 103 }
sub ECONNRESET { 104 }
sub ENOBUFS { 105 }
sub EISCONN { 106 }
sub ENOTCONN { 107 }
sub ESHUTDOWN { 108 }
sub ETOOMANYREFS { 109 }
sub ETIMEDOUT { 110 }
sub ECONNREFUSED { 111 }
sub EHOSTDOWN { 112 }
sub EHOSTUNREACH { 113 }
sub EALREADY { 114 }
sub EINPROGRESS { 115 }
sub ESTALE { 116 }
sub EUCLEAN { 117 }
sub ENOTNAM { 118 }
sub ENAVAIL { 119 }
sub EISNAM { 120 }
sub EREMOTEIO { 121 }
sub EDQUOT { 122 }
sub ENOMEDIUM { 123 }
sub EMEDIUMTYPE { 124 }
sub ECANCELED { 125 }
sub ENOKEY { 126 }
sub EKEYEXPIRED { 127 }
sub EKEYREVOKED { 128 }
sub EKEYREJECTED { 129 }
sub EOWNERDEAD { 130 }
sub ENOTRECOVERABLE { 131 }

1;
