package Fcntl;

use strict;
use warnings;
use Exporter 'import';

our $VERSION = '1.15';

our @EXPORT_OK = qw(
    O_RDONLY O_WRONLY O_RDWR O_CREAT O_EXCL O_NOCTTY O_TRUNC
    O_APPEND O_NONBLOCK O_NDELAY O_SYNC O_FSYNC O_ASYNC
    O_DIRECT O_LARGEFILE O_DIRECTORY O_NOFOLLOW O_NOATIME
    O_CLOEXEC O_TMPFILE
    S_ISUID S_ISGID S_ISVTX S_IRUSR S_IWUSR S_IXUSR
    S_IRGRP S_IWGRP S_IXGRP S_IROTH S_IWOTH S_IXOTH
    F_DUPFD F_GETFD F_SETFD F_GETFL F_SETFL F_SETLK F_SETLKW F_GETLK
    F_SETOWN F_GETOWN F_SETSIG F_GETSIG F_SETLEASE F_GETLEASE
    F_NOTIFY F_DUPFD_CLOEXEC
    DN_ACCESS DN_MODIFY DN_CREATE DN_DELETE DN_RENAME DN_ATTRIB
    FAPPEND FSYNC FASYNC FCREAT FTRUNC FEXCL FNDELAY FNONBLOCK
);

# Define some common constants
sub O_RDONLY () { 0 }
sub O_WRONLY () { 1 }
sub O_RDWR () { 2 }
sub O_CREAT () { 64 }
sub O_EXCL () { 128 }
sub O_NOCTTY () { 256 }
sub O_TRUNC () { 512 }
sub O_APPEND () { 1024 }
sub O_NONBLOCK () { 2048 }

sub S_IRUSR () { 256 }
sub S_IWUSR () { 128 }
sub S_IXUSR () { 64 }
sub S_IRGRP () { 32 }
sub S_IWGRP () { 16 }
sub S_IXGRP () { 8 }
sub S_IROTH () { 4 }
sub S_IWOTH () { 2 }
sub S_IXOTH () { 1 }

1;